import type { KitManifest, KitToolHandler, KitExecutionContext } from '../types';
async function metaApi(action: string, params: Record<string, unknown>, ctx: KitExecutionContext, method = 'GET') {
  if (method === 'GET') { const q = new URLSearchParams({ action, ...Object.fromEntries(Object.entries(params).filter(([, v]) => v != null).map(([k, v]) => [k, String(v)])) }).toString(); const r = await ctx.fetch(`/api/meta-ads?${q}`); if (!r.ok) { const e = await r.json().catch(() => ({})); throw new Error(e.error || 'Meta error'); } return r.json(); }
  const r = await ctx.fetch('/api/meta-ads', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, ...params }) }); if (!r.ok) { const e = await r.json().catch(() => ({})); throw new Error(e.error || 'Meta error'); } return r.json();
}
const listCampaigns: KitToolHandler = async (input, ctx) => { const d = await metaApi('list-campaigns', { accountId: input.accountId }, ctx); const camps = d.data ?? []; const lines = camps.map((c: { name: string; status: string; objective: string; daily_budget: string }) => `- **${c.name}** — ${c.status} (${c.objective}) — $${(Number(c.daily_budget || 0) / 100).toFixed(0)}/day`); return { success: true, data: camps, displayMarkdown: `## Meta Campaigns (${camps.length})\n\n${lines.join('\n')}` }; };
const campaignInsights: KitToolHandler = async (input, ctx) => { const d = await metaApi('campaign-insights', { campaignId: input.campaignId, datePreset: input.dateRange }, ctx); const row = d.data?.[0]; return { success: true, data: d, displayMarkdown: row ? `## Campaign Insights\n\n- **Impressions:** ${row.impressions}\n- **Clicks:** ${row.clicks}\n- **CTR:** ${row.ctr}\n- **Spend:** $${row.spend}\n- **Reach:** ${row.reach}` : 'No data.' }; };
const accountInsights: KitToolHandler = async (input, ctx) => { const d = await metaApi('account-insights', { accountId: input.accountId, datePreset: input.dateRange, breakdown: input.breakdown }, ctx); const row = d.data?.[0]; return { success: true, data: d, displayMarkdown: row ? `## Account Insights\n\n- **Impressions:** ${row.impressions}\n- **Clicks:** ${row.clicks}\n- **Spend:** $${row.spend}\n- **Reach:** ${row.reach}` : 'No data.' }; };
const listAudiences: KitToolHandler = async (input, ctx) => { const d = await metaApi('list-audiences', { accountId: input.accountId }, ctx); const auds = d.data ?? []; const lines = auds.map((a: { name: string; approximate_count: number; subtype: string }) => `- **${a.name}** (~${a.approximate_count?.toLocaleString()}) — ${a.subtype}`); return { success: true, data: auds, displayMarkdown: `## Audiences (${auds.length})\n\n${lines.join('\n')}` }; };
const igAccount: KitToolHandler = async (input, ctx) => { const d = await metaApi('instagram-account', { pageId: input.pageId }, ctx); const ig = d.instagram_business_account; return { success: true, data: ig, displayMarkdown: ig ? `## @${ig.username}\n\n- **Followers:** ${ig.followers_count?.toLocaleString()}\n- **Posts:** ${ig.media_count}\n- **Bio:** ${ig.biography}` : 'No Instagram account linked.' }; };
const igMedia: KitToolHandler = async (input, ctx) => { const d = await metaApi('instagram-media', { igAccountId: input.igAccountId, limit: input.limit ?? 10 }, ctx); const media = d.data ?? []; const lines = media.map((m: { caption: string; media_type: string; like_count: number; comments_count: number; permalink: string }) => `- **${m.media_type}** — ${m.like_count}❤ ${m.comments_count}💬 — ${m.caption?.slice(0, 60) || 'no caption'}`); return { success: true, data: media, displayMarkdown: `## Instagram Posts (${media.length})\n\n${lines.join('\n')}` }; };
const metaOverview: KitToolHandler = async (input, ctx) => { const d = await metaApi('overview', { accountId: input.accountId }, ctx); return { success: true, data: d, displayMarkdown: `## Meta Ads\n\n- **Account:** ${d.account} (${d.currency})\n- **Total Spent:** $${d.total_spent}\n- **Impressions (7d):** ${d.impressions_7d}\n- **Clicks (7d):** ${d.clicks_7d}\n- **Spend (7d):** $${d.spend_7d}` }; };
// CRUD handlers
const createCampaign: KitToolHandler = async (input, ctx) => { const d = await metaApi('create-campaign', { accountId: input.accountId, name: input.name, objective: input.objective, daily_budget: input.dailyBudget, status: input.status }, ctx, 'POST'); return { success: true, data: d, displayMarkdown: `Campaign created: **${input.name}** (${input.objective || 'AWARENESS'})` }; };
const updateCampaign: KitToolHandler = async (input, ctx) => { const d = await metaApi('update-campaign', { campaignId: input.campaignId, name: input.name, status: input.status, daily_budget: input.dailyBudget }, ctx, 'POST'); return { success: true, data: d, displayMarkdown: `Campaign updated: ${input.campaignId}` }; };
const createAdSet: KitToolHandler = async (input, ctx) => { const d = await metaApi('create-ad-set', { campaignId: input.campaignId, name: input.name, daily_budget: input.dailyBudget, optimization_goal: input.optimizationGoal, targeting: input.targeting, status: input.status }, ctx, 'POST'); return { success: true, data: d, displayMarkdown: `Ad set created: **${input.name}**` }; };
const createAd: KitToolHandler = async (input, ctx) => { const d = await metaApi('create-ad', { accountId: input.accountId, adSetId: input.adSetId, name: input.name, creative: input.creative, status: input.status }, ctx, 'POST'); return { success: true, data: d, displayMarkdown: `Ad created: **${input.name}**` }; };
const listCreatives: KitToolHandler = async (input, ctx) => { const d = await metaApi('list-creatives', { accountId: input.accountId }, ctx); const creatives = d.data ?? []; return { success: true, data: creatives, displayMarkdown: `## Creatives (${creatives.length})\n\n${creatives.slice(0, 10).map((c: { name: string; id: string }) => `- **${c.name}** (\`${c.id}\`)`).join('\n')}` }; };
const listPixels: KitToolHandler = async (input, ctx) => { const d = await metaApi('list-pixels', { accountId: input.accountId }, ctx); const pixels = d.data ?? []; return { success: true, data: pixels, displayMarkdown: `## Pixels (${pixels.length})\n\n${pixels.map((p: { name: string; id: string }) => `- **${p.name}** (\`${p.id}\`)`).join('\n')}` }; };
const createLookalike: KitToolHandler = async (input, ctx) => { const d = await metaApi('create-lookalike', { accountId: input.accountId, sourceAudienceId: input.sourceAudienceId, country: input.country, ratio: input.ratio }, ctx, 'POST'); return { success: true, data: d, displayMarkdown: `Lookalike audience created from source ${input.sourceAudienceId}` }; };
const listLeadForms: KitToolHandler = async (input, ctx) => { const d = await metaApi('list-lead-forms', { pageId: input.pageId }, ctx); const forms = d.data ?? []; return { success: true, data: forms, displayMarkdown: `## Lead Forms (${forms.length})\n\n${forms.map((f: { name: string; leads_count: number }) => `- **${f.name}** (${f.leads_count} leads)`).join('\n')}` }; };
const getLeads: KitToolHandler = async (input, ctx) => { const d = await metaApi('get-leads', { formId: input.formId }, ctx); const leads = d.data ?? []; return { success: true, data: leads, displayMarkdown: `## Leads (${leads.length})\n\n\`\`\`json\n${JSON.stringify(leads.slice(0, 5), null, 2).slice(0, 2000)}\n\`\`\`` }; };
const listCatalogs: KitToolHandler = async (input, ctx) => { const d = await metaApi('list-catalogs', { accountId: input.accountId }, ctx); const cats = d.data ?? []; return { success: true, data: cats, displayMarkdown: `## Catalogs (${cats.length})\n\n${cats.map((c: { name: string; product_count: number }) => `- **${c.name}** (${c.product_count} products)`).join('\n')}` }; };
const igInsights: KitToolHandler = async (input, ctx) => { const d = await metaApi('instagram-insights', { igAccountId: input.igAccountId, metric: input.metric, period: input.period }, ctx); return { success: true, data: d, displayMarkdown: `## Instagram Insights\n\n\`\`\`json\n${JSON.stringify(d.data?.slice(0, 5), null, 2).slice(0, 2000)}\n\`\`\`` }; };
export const manifest: KitManifest = {
  id: 'meta-ads', name: 'Meta Ads (Facebook + Instagram)', version: '2.0.0',
  description: 'Meta Marketing — FULL API: campaigns CRUD, ad sets CRUD, ads CRUD, creatives, pixels, lookalike audiences, lead forms, catalogs, Instagram business + insights.',
  author: 'MCV', capabilities: ['network', 'credentials'], runtime: 'inline', ventureScope: '*',
  instructions: 'Use meta ads tools for full Facebook/Instagram ad management: create/update campaigns, ad sets, ads, manage pixels, audiences, lead forms, and product catalogs.',
  tools: [
    { name: 'meta_campaigns', description: 'List campaigns.', input_schema: { type: 'object', properties: { accountId: { type: 'string' } } } },
    { name: 'meta_create_campaign', description: 'Create a campaign.', input_schema: { type: 'object', properties: { accountId: { type: 'string' }, name: { type: 'string' }, objective: { type: 'string', description: 'OUTCOME_AWARENESS, OUTCOME_TRAFFIC, OUTCOME_LEADS, OUTCOME_SALES' }, dailyBudget: { type: 'number' }, status: { type: 'string' } }, required: ['name'] } },
    { name: 'meta_update_campaign', description: 'Update a campaign (name, status, budget).', input_schema: { type: 'object', properties: { campaignId: { type: 'string' }, name: { type: 'string' }, status: { type: 'string', description: 'ACTIVE, PAUSED' }, dailyBudget: { type: 'number' } }, required: ['campaignId'] } },
    { name: 'meta_create_ad_set', description: 'Create an ad set in a campaign.', input_schema: { type: 'object', properties: { campaignId: { type: 'string' }, name: { type: 'string' }, dailyBudget: { type: 'number' }, optimizationGoal: { type: 'string' }, targeting: { type: 'object' } }, required: ['campaignId', 'name'] } },
    { name: 'meta_create_ad', description: 'Create an ad in an ad set.', input_schema: { type: 'object', properties: { adSetId: { type: 'string' }, name: { type: 'string' }, creative: { type: 'object' } }, required: ['adSetId', 'name', 'creative'] } },
    { name: 'meta_campaign_insights', description: 'Campaign performance metrics.', input_schema: { type: 'object', properties: { campaignId: { type: 'string' }, dateRange: { type: 'string' } }, required: ['campaignId'] } },
    { name: 'meta_account_insights', description: 'Account-level insights with breakdowns.', input_schema: { type: 'object', properties: { accountId: { type: 'string' }, dateRange: { type: 'string' }, breakdown: { type: 'string' } } } },
    { name: 'meta_audiences', description: 'List custom audiences.', input_schema: { type: 'object', properties: { accountId: { type: 'string' } } } },
    { name: 'meta_create_lookalike', description: 'Create a lookalike audience.', input_schema: { type: 'object', properties: { sourceAudienceId: { type: 'string' }, country: { type: 'string' }, ratio: { type: 'string', description: '0.01 to 0.20' } }, required: ['sourceAudienceId', 'country'] } },
    { name: 'meta_creatives', description: 'List ad creatives.', input_schema: { type: 'object', properties: { accountId: { type: 'string' } } } },
    { name: 'meta_pixels', description: 'List tracking pixels.', input_schema: { type: 'object', properties: { accountId: { type: 'string' } } } },
    { name: 'meta_lead_forms', description: 'List lead gen forms on a page.', input_schema: { type: 'object', properties: { pageId: { type: 'string' } }, required: ['pageId'] } },
    { name: 'meta_get_leads', description: 'Get leads from a form.', input_schema: { type: 'object', properties: { formId: { type: 'string' } }, required: ['formId'] } },
    { name: 'meta_catalogs', description: 'List product catalogs.', input_schema: { type: 'object', properties: { accountId: { type: 'string' } } } },
    { name: 'meta_instagram_account', description: 'Get Instagram business account.', input_schema: { type: 'object', properties: { pageId: { type: 'string' } }, required: ['pageId'] } },
    { name: 'meta_instagram_media', description: 'List Instagram posts.', input_schema: { type: 'object', properties: { igAccountId: { type: 'string' }, limit: { type: 'number' } }, required: ['igAccountId'] } },
    { name: 'meta_instagram_insights', description: 'Instagram account insights.', input_schema: { type: 'object', properties: { igAccountId: { type: 'string' }, metric: { type: 'string' }, period: { type: 'string' } }, required: ['igAccountId'] } },
    { name: 'meta_overview', description: 'Account overview.', input_schema: { type: 'object', properties: { accountId: { type: 'string' } } } },
  ],
};
export const handlers: Record<string, KitToolHandler> = {
  meta_campaigns: listCampaigns, meta_create_campaign: createCampaign, meta_update_campaign: updateCampaign,
  meta_create_ad_set: createAdSet, meta_create_ad: createAd, meta_campaign_insights: campaignInsights,
  meta_account_insights: accountInsights, meta_audiences: listAudiences, meta_create_lookalike: createLookalike,
  meta_creatives: listCreatives, meta_pixels: listPixels, meta_lead_forms: listLeadForms, meta_get_leads: getLeads,
  meta_catalogs: listCatalogs, meta_instagram_account: igAccount, meta_instagram_media: igMedia,
  meta_instagram_insights: igInsights, meta_overview: metaOverview,
};
