import type { KitManifest, KitToolHandler, KitExecutionContext } from '../types';
async function metaApi(action: string, params: Record<string, unknown>, ctx: KitExecutionContext, method = 'GET') {
  if (method === 'GET') { const q = new URLSearchParams({ action, ...Object.fromEntries(Object.entries(params).filter(([, v]) => v != null).map(([k, v]) => [k, String(v)])) }).toString(); const r = await ctx.fetch(`/api/meta-ads?${q}`); if (!r.ok) { const e = await r.json().catch(() => ({})); throw new Error(e.error || 'Meta error'); } return r.json(); }
  const r = await ctx.fetch('/api/meta-ads', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, ...params }) }); if (!r.ok) { const e = await r.json().catch(() => ({})); throw new Error(e.error || 'Meta error'); } return r.json();
}
const listCampaigns: KitToolHandler = async (input, ctx) => { const d = await metaApi('list-campaigns', { accountId: input.accountId }, ctx); const camps = d.data ?? []; const lines = camps.map((c: { name: string; status: string; objective: string; daily_budget: string }) => `- **${c.name}** — ${c.status} (${c.objective}) — $${(Number(c.daily_budget || 0) / 100).toFixed(0)}/day`); return { success: true, data: camps, displayMarkdown: `## Meta Campaigns (${camps.length})\n\n${lines.join('\n')}` }; };
const campaignInsights: KitToolHandler = async (input, ctx) => { const d = await metaApi('campaign-insights', { campaignId: input.campaignId, datePreset: input.dateRange }, ctx); const row = d.data?.[0]; return { success: true, data: d, displayMarkdown: row ? `## Campaign Insights\n\n- **Impressions:** ${row.impressions}\n- **Clicks:** ${row.clicks}\n- **CTR:** ${row.ctr}\n- **Spend:** $${row.spend}\n- **Reach:** ${row.reach}` : 'No data.' }; };
const accountInsights: KitToolHandler = async (input, ctx) => { const d = await metaApi('account-insights', { accountId: input.accountId, datePreset: input.dateRange, breakdown: input.breakdown }, ctx); const row = d.data?.[0]; return { success: true, data: d, displayMarkdown: row ? `## Account Insights\n\n- **Impressions:** ${row.impressions}\n- **Clicks:** ${row.clicks}\n- **Spend:** $${row.spend}\n- **Reach:** ${row.reach}` : 'No data.' }; };
const listAudiences: KitToolHandler = async (input, ctx) => { const d = await metaApi('list-audiences', { accountId: input.accountId }, ctx); const auds = d.data ?? []; const lines = auds.map((a: { name: string; approximate_count: number; subtype: string }) => `- **${a.name}** (~${a.approximate_count?.toLocaleString()}) — ${a.subtype}`); return { success: true, data: auds, displayMarkdown: `## Audiences (${auds.length})\n\n${lines.join('\n')}` }; };
const igAccount: KitToolHandler = async (input, ctx) => { const d = await metaApi('instagram-account', { pageId: input.pageId }, ctx); const ig = d.instagram_business_account; return { success: true, data: ig, displayMarkdown: ig ? `## @${ig.username}\n\n- **Followers:** ${ig.followers_count?.toLocaleString()}\n- **Posts:** ${ig.media_count}\n- **Bio:** ${ig.biography}` : 'No Instagram account linked.' }; };
const igMedia: KitToolHandler = async (input, ctx) => { const d = await metaApi('instagram-media', { igAccountId: input.igAccountId, limit: input.limit ?? 10 }, ctx); const media = d.data ?? []; const lines = media.map((m: { caption: string; media_type: string; like_count: number; comments_count: number; permalink: string }) => `- **${m.media_type}** — ${m.like_count}❤ ${m.comments_count}💬 — ${m.caption?.slice(0, 60) || 'no caption'}`); return { success: true, data: media, displayMarkdown: `## Instagram Posts (${media.length})\n\n${lines.join('\n')}` }; };
const metaOverview: KitToolHandler = async (input, ctx) => { const d = await metaApi('overview', { accountId: input.accountId }, ctx); return { success: true, data: d, displayMarkdown: `## Meta Ads\n\n- **Account:** ${d.account} (${d.currency})\n- **Total Spent:** $${d.total_spent}\n- **Impressions (7d):** ${d.impressions_7d}\n- **Clicks (7d):** ${d.clicks_7d}\n- **Spend (7d):** $${d.spend_7d}` }; };
export const manifest: KitManifest = {
  id: 'meta-ads', name: 'Meta Ads (Facebook + Instagram)', version: '1.0.0',
  description: 'Meta Marketing — campaigns, ad sets, ads, audiences, insights, pages, Instagram business, and cross-platform reporting.',
  author: 'MCV', capabilities: ['network', 'credentials'], runtime: 'inline', ventureScope: '*',
  instructions: 'Use meta ads tools for Facebook/Instagram ad campaign management, audience targeting, insights reporting, and Instagram content analytics.',
  tools: [
    { name: 'meta_campaigns', description: 'List Meta ad campaigns.', input_schema: { type: 'object', properties: { accountId: { type: 'string' } } } },
    { name: 'meta_campaign_insights', description: 'Get campaign performance metrics.', input_schema: { type: 'object', properties: { campaignId: { type: 'string' }, dateRange: { type: 'string', description: 'last_7d, last_30d, last_90d' } }, required: ['campaignId'] } },
    { name: 'meta_account_insights', description: 'Get account-level ad insights.', input_schema: { type: 'object', properties: { accountId: { type: 'string' }, dateRange: { type: 'string' }, breakdown: { type: 'string', description: 'age, gender, platform_position' } } } },
    { name: 'meta_audiences', description: 'List custom audiences.', input_schema: { type: 'object', properties: { accountId: { type: 'string' } } } },
    { name: 'meta_instagram_account', description: 'Get Instagram business account linked to a page.', input_schema: { type: 'object', properties: { pageId: { type: 'string' } }, required: ['pageId'] } },
    { name: 'meta_instagram_media', description: 'List Instagram posts with engagement.', input_schema: { type: 'object', properties: { igAccountId: { type: 'string' }, limit: { type: 'number' } }, required: ['igAccountId'] } },
    { name: 'meta_overview', description: 'Meta Ads overview: account, spend, performance.', input_schema: { type: 'object', properties: { accountId: { type: 'string' } } } },
  ],
};
export const handlers: Record<string, KitToolHandler> = { meta_campaigns: listCampaigns, meta_campaign_insights: campaignInsights, meta_account_insights: accountInsights, meta_audiences: listAudiences, meta_instagram_account: igAccount, meta_instagram_media: igMedia, meta_overview: metaOverview };
