// MCV One — Ad Placement Intelligence System
// TikTok ad format specifications

import type { AdFormat } from '../types';

export const TIKTOK_AD_FORMATS: AdFormat[] = [
  {
    id: 'tiktok-ads:in-feed:image',
    platform: 'tiktok-ads',
    placement: 'in-feed',
    name: 'In-Feed: Image',
    mediaType: 'image',
    description: 'Static image ad appearing in the TikTok For You feed. Supports vertical, horizontal, and square orientations.',
    imageSpec: {
      formats: ['jpg', 'png'],
      maxFileSizeMb: 5,
      dimensions: [
        { width: 720, height: 1280, label: 'Vertical 9:16 (recommended)' },
        { width: 1280, height: 720, label: 'Horizontal 16:9' },
        { width: 1280, height: 1280, label: 'Square 1:1' },
      ],
      aspectRatios: [
        { ratio: '9:16', minWidth: 720, minHeight: 1280 },
        { ratio: '16:9', minWidth: 1280, minHeight: 720 },
        { ratio: '1:1', minWidth: 1280, minHeight: 1280 },
      ],
    },
    textSpecs: [
      { field: 'ad_text', maxChars: 100, notes: 'Primary ad copy displayed with the image' },
      { field: 'display_name', maxChars: 40, notes: 'Brand or app name shown on the ad' },
    ],
    callToAction: [
      'Shop Now', 'Learn More', 'Sign Up', 'Download', 'Contact Us',
      'Apply Now', 'Book Now', 'Get Quote', 'Subscribe', 'Order Now',
    ],
    tips: [
      'Vertical (9:16) images fill the full screen and perform best on TikTok',
      'Use bold, high-contrast visuals that feel native to the platform',
      'Keep ad text short and punchy — users scroll fast',
      'Match the visual style of organic TikTok content for higher engagement',
    ],
    docsUrl: 'https://ads.tiktok.com/help/article/ad-specifications',
    verifiedAt: '2026-03-15',
  },
  {
    id: 'tiktok-ads:in-feed:video',
    platform: 'tiktok-ads',
    placement: 'in-feed',
    name: 'In-Feed: Video',
    mediaType: 'video',
    description: 'Video ad appearing natively in the TikTok For You feed. The most common TikTok ad format — plays full-screen with sound.',
    videoSpec: {
      formats: ['mp4', 'mov', 'avi'],
      maxFileSizeMb: 500,
      dimensions: [
        { width: 720, height: 1280, label: 'Vertical 9:16' },
        { width: 1280, height: 720, label: 'Horizontal 16:9' },
        { width: 1280, height: 1280, label: 'Square 1:1' },
      ],
      aspectRatios: [
        { ratio: '9:16', minWidth: 720, minHeight: 1280 },
        { ratio: '16:9', minWidth: 1280, minHeight: 720 },
        { ratio: '1:1', minWidth: 1280, minHeight: 1280 },
      ],
      minDurationSec: 5,
      maxDurationSec: 60,
      recommendedDurationSec: 27,
      audioRequired: true,
      captionsRecommended: true,
    },
    textSpecs: [
      { field: 'ad_text', maxChars: 100, notes: 'Primary ad copy overlaid on the video' },
      { field: 'display_name', maxChars: 40, notes: 'Brand or app name shown on the ad' },
    ],
    callToAction: [
      'Shop Now', 'Learn More', 'Sign Up', 'Download', 'Contact Us',
      'Apply Now', 'Book Now', 'Get Quote', 'Subscribe', 'Order Now',
    ],
    tips: [
      'Optimal duration is 21-34 seconds for the best cost-per-action',
      'Use vertical (9:16) for full-screen immersive experience',
      'Hook viewers in the first 2 seconds — TikTok users scroll fast',
      'Use trending sounds and music to boost organic reach',
      'Make it feel like organic content, not a polished ad',
    ],
    docsUrl: 'https://ads.tiktok.com/help/article/ad-specifications',
    verifiedAt: '2026-03-15',
  },
  {
    id: 'tiktok-ads:topview',
    platform: 'tiktok-ads',
    placement: 'topview',
    name: 'TopView: Video',
    mediaType: 'video',
    description: 'Premium full-screen video ad that appears as the first in-feed post when users open TikTok. Maximum visibility placement.',
    videoSpec: {
      formats: ['mp4', 'mov'],
      maxFileSizeMb: 500,
      dimensions: [
        { width: 1080, height: 1920, label: 'Vertical 9:16 (required)' },
      ],
      aspectRatios: [
        { ratio: '9:16', minWidth: 1080, minHeight: 1920 },
      ],
      minDurationSec: 5,
      maxDurationSec: 60,
      recommendedDurationSec: 15,
      audioRequired: true,
      captionsRecommended: true,
    },
    textSpecs: [
      { field: 'ad_text', maxChars: 100, notes: 'Primary ad copy overlaid on the video' },
      { field: 'display_name', maxChars: 40, notes: 'Brand or app name shown on the ad' },
    ],
    callToAction: [
      'Shop Now', 'Learn More', 'Sign Up', 'Download', 'Watch More',
    ],
    policyNotes: [
      'Premium placement — requires reservation-based buying',
      'Guaranteed first-in-feed position when app is opened',
      '1080x1920 (9:16) is required for TopView',
    ],
    tips: [
      'TopView has the highest attention and recall of any TikTok format',
      'Use cinematic, high-quality creative for this premium placement',
      'Sound is on by default — design with audio as a key element',
      'Brand within the first 3 seconds for maximum recall',
    ],
    docsUrl: 'https://ads.tiktok.com/help/article/ad-specifications',
    verifiedAt: '2026-03-15',
  },
  {
    id: 'tiktok-ads:spark-ads',
    platform: 'tiktok-ads',
    placement: 'in-feed',
    name: 'Spark Ads: Video',
    mediaType: 'video',
    description: 'Boosted organic TikTok post from your brand or a creator. Uses the original creator\'s video and profile, maintaining authenticity.',
    videoSpec: {
      formats: ['mp4', 'mov'],
      maxFileSizeMb: 500,
      minDurationSec: 5,
      maxDurationSec: 60,
      aspectRatios: [
        { ratio: '9:16', minWidth: 720, minHeight: 1280 },
      ],
    },
    textSpecs: [
      { field: 'ad_text', maxChars: 100, notes: 'Text from original post is used; can be edited when using own posts' },
    ],
    callToAction: [
      'Shop Now', 'Learn More', 'Sign Up', 'Download', 'Contact Us',
      'Apply Now', 'Book Now', 'Get Quote',
    ],
    policyNotes: [
      'Requires authorization code from the original creator',
      'Uses the creator\'s profile and video natively',
      'Engagement (likes, comments, shares) goes to the original post',
      'Creator must grant access via Spark Ads authorization',
    ],
    tips: [
      'Spark Ads have higher engagement than standard in-feed ads because they feel organic',
      'Partner with creators whose audience matches your target demographic',
      'Boosting existing high-performing organic posts is the easiest way to start',
      'All engagement accrues to the original post, building long-term value',
    ],
    docsUrl: 'https://ads.tiktok.com/help/article/spark-ads',
    verifiedAt: '2026-03-15',
  },
  {
    id: 'tiktok-ads:collection-ads',
    platform: 'tiktok-ads',
    placement: 'in-feed',
    name: 'Collection Ads: Video + Product Cards',
    mediaType: 'video',
    description: 'In-feed video ad paired with swipeable product cards. Combines video storytelling with instant product browsing.',
    videoSpec: {
      formats: ['mp4', 'mov', 'avi'],
      maxFileSizeMb: 500,
      dimensions: [
        { width: 720, height: 1280, label: 'Vertical 9:16' },
        { width: 1280, height: 720, label: 'Horizontal 16:9' },
        { width: 1280, height: 1280, label: 'Square 1:1' },
      ],
      aspectRatios: [
        { ratio: '9:16', minWidth: 720, minHeight: 1280 },
        { ratio: '16:9', minWidth: 1280, minHeight: 720 },
        { ratio: '1:1', minWidth: 1280, minHeight: 1280 },
      ],
      minDurationSec: 5,
      maxDurationSec: 60,
      recommendedDurationSec: 27,
      audioRequired: true,
      captionsRecommended: true,
    },
    textSpecs: [
      { field: 'ad_text', maxChars: 100, notes: 'Primary ad copy for the video portion' },
      { field: 'display_name', maxChars: 40, notes: 'Brand or app name shown on the ad' },
    ],
    callToAction: [
      'Shop Now', 'Learn More', 'Buy Now', 'View Products',
    ],
    policyNotes: [
      'Minimum 3 product cards, maximum 20 product cards',
      'Product cards are pulled from your TikTok product catalog',
      'Requires TikTok Shop or product catalog integration',
    ],
    tips: [
      'Feature your best-selling products in the first 3 card positions',
      'Use the video to create desire, then let product cards drive conversion',
      'Ensure product images are high-quality and consistent in style',
      'Collection ads work best for e-commerce and retail campaigns',
    ],
    docsUrl: 'https://ads.tiktok.com/help/article/ad-specifications',
    verifiedAt: '2026-03-15',
  },
  {
    id: 'tiktok-ads:branded-effects',
    platform: 'tiktok-ads',
    placement: 'camera',
    name: 'Branded Effects',
    mediaType: 'responsive',
    description: 'Custom AR effects (filters, stickers, gamified lenses) that users interact with using the TikTok camera. Drives UGC and brand engagement.',
    textSpecs: [],
    callToAction: [
      'Try Now', 'Use Effect', 'Create',
    ],
    policyNotes: [
      'No standard image/video dimensions — effects are interactive AR',
      'Supports 2D, 3D, and gamified effect types',
      'Requires TikTok Effect House or agency partner for creation',
      'Effects can last up to 10 days as a sponsored placement',
    ],
    tips: [
      'Gamified effects drive the highest participation and UGC',
      'Design effects that are fun and shareable — users should want to use them',
      'Pair Branded Effects with a Hashtag Challenge for maximum virality',
      'Keep the brand integration natural — overly branded effects underperform',
    ],
    docsUrl: 'https://ads.tiktok.com/help/article/branded-effect',
    verifiedAt: '2026-03-15',
  },
  {
    id: 'tiktok-ads:pangle:image',
    platform: 'tiktok-ads',
    placement: 'pangle',
    name: 'Pangle: Image',
    mediaType: 'image',
    description: 'Image ad served across TikTok\'s Pangle audience network of third-party apps. Extends reach beyond the TikTok app.',
    imageSpec: {
      formats: ['jpg', 'png'],
      maxFileSizeMb: 5,
      dimensions: [
        { width: 640, height: 640, label: 'Square 1:1' },
        { width: 1200, height: 628, label: 'Landscape 1.91:1' },
      ],
      aspectRatios: [
        { ratio: '1:1', minWidth: 640, minHeight: 640 },
        { ratio: '1.91:1', minWidth: 1200, minHeight: 628 },
      ],
    },
    textSpecs: [
      { field: 'title', maxChars: 90, notes: 'Ad title displayed with the image' },
      { field: 'description', maxChars: 100, notes: 'Supporting description text' },
    ],
    callToAction: [
      'Shop Now', 'Learn More', 'Sign Up', 'Download', 'Install Now',
      'Play Now', 'Contact Us',
    ],
    tips: [
      'Pangle inventory varies widely — test both square and landscape formats',
      'Creative should work well at small sizes since placements vary across apps',
      'Use clear, bold visuals that communicate the message at a glance',
      'Pangle is especially effective for app install campaigns',
    ],
    docsUrl: 'https://ads.tiktok.com/help/article/ad-specifications',
    verifiedAt: '2026-03-15',
  },
  {
    id: 'tiktok-ads:pangle:video',
    platform: 'tiktok-ads',
    placement: 'pangle',
    name: 'Pangle: Video',
    mediaType: 'video',
    description: 'Video ad served across TikTok\'s Pangle audience network. Includes rewarded video, interstitial, and native placements in third-party apps.',
    videoSpec: {
      formats: ['mp4', 'mov'],
      maxFileSizeMb: 500,
      dimensions: [
        { width: 640, height: 640, label: 'Square 1:1' },
        { width: 1280, height: 720, label: 'Landscape 16:9' },
      ],
      aspectRatios: [
        { ratio: '1:1', minWidth: 640, minHeight: 640 },
        { ratio: '16:9', minWidth: 1280, minHeight: 720 },
      ],
      minDurationSec: 5,
      maxDurationSec: 60,
      recommendedDurationSec: 15,
      captionsRecommended: true,
    },
    textSpecs: [
      { field: 'title', maxChars: 90, notes: 'Ad title displayed with the video' },
      { field: 'description', maxChars: 100, notes: 'Supporting description text' },
    ],
    callToAction: [
      'Shop Now', 'Learn More', 'Sign Up', 'Download', 'Install Now',
      'Play Now', 'Contact Us',
    ],
    tips: [
      'Rewarded video placements have the highest completion rates on Pangle',
      'Design for both orientations since Pangle inventory includes various app layouts',
      'Keep videos under 30 seconds for best performance across placements',
      'Include a strong CTA since Pangle viewers are already engaged in-app',
    ],
    docsUrl: 'https://ads.tiktok.com/help/article/ad-specifications',
    verifiedAt: '2026-03-15',
  },
];
