import type { AdFormat } from '../types';

export const YOUTUBE_AD_FORMATS: AdFormat[] = [
  {
    id: 'youtube-ads:skippable-in-stream:video',
    platform: 'youtube-ads',
    placement: 'skippable-in-stream',
    name: 'Skippable In-Stream (Pre-roll)',
    mediaType: 'video',
    description:
      'Plays before, during, or after other videos. Viewers can skip after 5 seconds. Charged on CPV or CPM basis.',
    videoSpec: {
      formats: ['mp4', 'mov'],
      maxFileSizeMb: 256,
      minDurationSec: 12,
      recommendedDurationSec: 15,
      dimensions: [
        { width: 1920, height: 1080, label: 'Full HD' },
        { width: 1280, height: 720, label: 'HD' },
      ],
      aspectRatios: [{ ratio: '16:9' }],
      captionsRecommended: true,
    },
    imageSpec: {
      formats: ['jpg', 'png'],
      maxFileSizeMb: 0.15,
      dimensions: [{ width: 300, height: 60, label: 'Companion Banner' }],
    },
    textSpecs: [],
    tips: [
      'Hook viewers in the first 5 seconds before the skip button appears.',
      'Include a clear call-to-action within the first 15 seconds for maximum impact.',
      'Add a 300x60 companion banner to reinforce your message while the video plays.',
    ],
    docsUrl: 'https://support.google.com/google-ads/answer/2375497',
    verifiedAt: '2026-04-05',
  },
  {
    id: 'youtube-ads:non-skippable-in-stream:video',
    platform: 'youtube-ads',
    placement: 'non-skippable-in-stream',
    name: 'Non-Skippable In-Stream',
    mediaType: 'video',
    description:
      'Plays before, during, or after other videos. Viewers must watch the entire ad. Ideal for brand awareness.',
    videoSpec: {
      formats: ['mp4'],
      maxFileSizeMb: 256,
      minDurationSec: 15,
      maxDurationSec: 20,
      dimensions: [{ width: 1920, height: 1080, label: 'Full HD' }],
      aspectRatios: [{ ratio: '16:9' }],
      captionsRecommended: true,
    },
    textSpecs: [],
    tips: [
      'Keep messaging concise — you have exactly 15-20 seconds with a captive audience.',
      'Front-load your brand identity since viewers cannot skip.',
      'Use captions for accessibility and sound-off environments.',
    ],
    docsUrl: 'https://support.google.com/google-ads/answer/2375464',
    verifiedAt: '2026-04-05',
  },
  {
    id: 'youtube-ads:bumper:video',
    platform: 'youtube-ads',
    placement: 'bumper',
    name: 'Bumper Ad',
    mediaType: 'video',
    description:
      'Non-skippable 6-second ad that plays before a video. Optimized for reach and frequency at low cost.',
    videoSpec: {
      formats: ['mp4'],
      maxFileSizeMb: 256,
      maxDurationSec: 6,
      dimensions: [{ width: 1920, height: 1080, label: 'Full HD' }],
      aspectRatios: [{ ratio: '16:9' }],
      captionsRecommended: true,
    },
    textSpecs: [],
    tips: [
      'Focus on a single message — 6 seconds is only enough for one idea.',
      'Pair bumper campaigns with longer in-stream ads for a full-funnel approach.',
      'Use bold visuals and quick cuts to maximize impact in the short window.',
    ],
    docsUrl: 'https://support.google.com/google-ads/answer/2375464',
    verifiedAt: '2026-04-05',
  },
  {
    id: 'youtube-ads:in-feed:image',
    platform: 'youtube-ads',
    placement: 'in-feed',
    name: 'In-Feed (Discovery) Ad',
    mediaType: 'image',
    description:
      'Appears alongside related YouTube videos, in search results, or on the YouTube homepage. Users click to watch.',
    imageSpec: {
      formats: ['jpg', 'png'],
      maxFileSizeMb: 2,
      dimensions: [{ width: 1280, height: 720, label: 'Thumbnail' }],
    },
    textSpecs: [
      { field: 'headline', maxChars: 100, notes: 'Primary clickable title' },
      { field: 'description1', maxChars: 35, notes: 'First line of description' },
      { field: 'description2', maxChars: 35, notes: 'Second line of description' },
    ],
    tips: [
      'Use a high-contrast, eye-catching thumbnail — it is the primary driver of clicks.',
      'Write headlines that spark curiosity without being clickbait.',
      'Test multiple thumbnail and headline combinations to find the best CTR.',
    ],
    docsUrl: 'https://support.google.com/google-ads/answer/6244622',
    verifiedAt: '2026-04-05',
  },
  {
    id: 'youtube-ads:shorts:video',
    platform: 'youtube-ads',
    placement: 'shorts',
    name: 'YouTube Shorts Ad',
    mediaType: 'video',
    description:
      'Vertical video ads shown between Shorts. Immersive full-screen experience on mobile devices.',
    videoSpec: {
      formats: ['mp4'],
      maxFileSizeMb: 256,
      maxDurationSec: 60,
      dimensions: [{ width: 1080, height: 1920, label: 'Vertical Full HD' }],
      aspectRatios: [{ ratio: '9:16' }],
      captionsRecommended: true,
    },
    textSpecs: [],
    policyNotes: ['Vertical (9:16) orientation is required.'],
    tips: [
      'Create native-feeling vertical content — repurposed landscape video performs poorly.',
      'Capture attention immediately; users swipe quickly through Shorts.',
      'Keep it under 30 seconds for best completion rates despite the 60-second limit.',
    ],
    docsUrl: 'https://support.google.com/youtube/answer/12499997',
    verifiedAt: '2026-04-05',
  },
  {
    id: 'youtube-ads:masthead:video',
    platform: 'youtube-ads',
    placement: 'masthead',
    name: 'YouTube Masthead',
    mediaType: 'video',
    description:
      'Premium placement at the top of the YouTube homepage. Autoplays muted for up to 30 seconds. Reservation-only.',
    videoSpec: {
      formats: ['mp4'],
      maxFileSizeMb: 256,
      minDurationSec: 15,
      maxDurationSec: 30,
      dimensions: [{ width: 1920, height: 1080, label: 'Full HD' }],
      aspectRatios: [{ ratio: '16:9' }],
      audioRequired: false,
      captionsRecommended: true,
    },
    textSpecs: [
      { field: 'headline', maxChars: 30, notes: 'Displayed beside the video' },
      { field: 'description', maxChars: 90, notes: 'Supporting text below the headline' },
    ],
    tips: [
      'Design for muted autoplay — rely on visuals and text overlays, not audio.',
      'This is a reservation buy; coordinate with your Google sales rep well in advance.',
      'Use the companion text fields to reinforce the video message.',
    ],
    docsUrl: 'https://support.google.com/google-ads/answer/9709826',
    verifiedAt: '2026-04-05',
  },
  {
    id: 'youtube-ads:overlay:image',
    platform: 'youtube-ads',
    placement: 'overlay',
    name: 'Overlay Ad',
    mediaType: 'image',
    description:
      'Semi-transparent overlay that appears on the lower 20% of a video. Desktop only. Viewers can close it.',
    imageSpec: {
      formats: ['jpg', 'png', 'gif'],
      maxFileSizeMb: 0.15,
      dimensions: [{ width: 480, height: 70, label: 'Overlay Banner' }],
    },
    textSpecs: [
      { field: 'display_url', maxChars: 35, notes: 'Visible URL shown on the overlay' },
    ],
    policyNotes: ['Text overlay ads are also supported as an alternative to image overlays.'],
    tips: [
      'Keep the design simple — the small 480x70 space demands clarity.',
      'Use a strong CTA since users can dismiss the overlay at any time.',
    ],
    docsUrl: 'https://support.google.com/google-ads/answer/2404196',
    verifiedAt: '2026-04-05',
  },
  {
    id: 'youtube-ads:display-companion:image',
    platform: 'youtube-ads',
    placement: 'display-companion',
    name: 'Display Companion Ad',
    mediaType: 'image',
    description:
      'A 300x250 image ad displayed beside the video player on desktop. Often paired with in-stream ads.',
    imageSpec: {
      formats: ['jpg', 'png', 'gif'],
      maxFileSizeMb: 0.15,
      dimensions: [{ width: 300, height: 250, label: 'Medium Rectangle' }],
    },
    textSpecs: [],
    tips: [
      'Ensure the companion creative visually matches the in-stream ad it accompanies.',
      'Include a clear CTA button to drive clicks from the sidebar placement.',
      'This format is desktop-only — plan your mobile strategy separately.',
    ],
    docsUrl: 'https://support.google.com/google-ads/answer/2404196',
    verifiedAt: '2026-04-05',
  },
];
