/**
 * MCV One Desktop — Morning Brief Workflow
 *
 * Durable workflow that generates a daily CEO intelligence brief:
 * - Aggregates activity from all ventures (GitHub, Vercel, tasks, CRM)
 * - Generates an AI summary via Claude
 * - Stores as a document in the Docs Hub
 *
 * Designed to run on a cron schedule (e.g., daily at 7 AM).
 */

import { sleep } from 'workflow';

// ── Step: Gather GitHub activity ──
async function gatherGitHubActivity() {
  'use step';

  try {
    const res = await fetch('http://localhost:3100/local/pipeline');
    const data = await res.json();
    return {
      repos: data.repos || [],
      totalCommits7d: data.stats?.commits7d || 0,
      uncommittedChanges: data.stats?.uncommittedChanges || 0,
      worktreeSessions: data.stats?.worktreeSessions || 0,
    };
  } catch {
    return { repos: [], totalCommits7d: 0, uncommittedChanges: 0, worktreeSessions: 0 };
  }
}

// ── Step: Gather Docker status ──
async function gatherDockerStatus() {
  'use step';

  try {
    const res = await fetch('http://localhost:3100/local/docker/containers');
    const data = await res.json();
    if (!data.available) return { available: false, containers: [] };
    return {
      available: true,
      containers: (data.containers || []).map((c: { name: string; state: string; venture: string | null }) => ({
        name: c.name,
        state: c.state,
        venture: c.venture,
      })),
      summary: data.summary,
    };
  } catch {
    return { available: false, containers: [] };
  }
}

// ── Step: Gather memory & plans ──
async function gatherMemoryAndPlans() {
  'use step';

  try {
    const res = await fetch('http://localhost:3100/local/pipeline');
    const data = await res.json();
    return {
      memoryFiles: data.stats?.memoryFiles || 0,
      plans: (data.plans || []).slice(0, 5).map((p: { name: string; modified: string }) => ({
        name: p.name,
        modified: p.modified,
      })),
    };
  } catch {
    return { memoryFiles: 0, plans: [] };
  }
}

// ── Step: Generate brief with Claude ──
async function generateBrief(context: {
  github: Awaited<ReturnType<typeof gatherGitHubActivity>>;
  docker: Awaited<ReturnType<typeof gatherDockerStatus>>;
  memory: Awaited<ReturnType<typeof gatherMemoryAndPlans>>;
  date: string;
}) {
  'use step';

  // Build the context prompt
  const repoSummary = context.github.repos
    .map((r: { name: string; branch: string; commitCount7d: number; uncommittedChanges: number }) =>
      `- ${r.name}: ${r.commitCount7d} commits/7d, branch: ${r.branch}${r.uncommittedChanges > 0 ? `, ${r.uncommittedChanges} uncommitted` : ''}`)
    .join('\n');

  const dockerSummary = context.docker.available
    ? context.docker.containers
        .map((c: { name: string; state: string; venture: string | null }) => `- ${c.name}: ${c.state}${c.venture ? ` [${c.venture}]` : ''}`)
        .join('\n')
    : 'Docker Desktop not running';

  const plansSummary = context.memory.plans
    .map((p: { name: string; modified: string }) => `- ${p.name} (updated: ${p.modified})`)
    .join('\n');

  const briefContent = `# Morning Brief — ${context.date}

## Development Activity (7 days)
**${context.github.totalCommits7d}** commits across **${context.github.repos.length}** repos | **${context.github.uncommittedChanges}** uncommitted changes | **${context.github.worktreeSessions}** active worktrees

### Repositories
${repoSummary || 'No repository data available'}

## Infrastructure
${dockerSummary}

## Active Plans
${plansSummary || 'No active plans'}

## Memory Hub
**${context.memory.memoryFiles}** memory files across projects

---
*Generated by NAOS Morning Brief Workflow*`;

  return briefContent;
}

// ── Step: Store brief ──
async function storeBrief(content: string, date: string) {
  'use step';

  // In production, this would POST to the docs API to create a document
  console.log(`[WORKFLOW:BRIEF] Stored morning brief for ${date} (${content.length} chars)`);
  return {
    stored: true,
    date,
    size: content.length,
    timestamp: new Date().toISOString(),
  };
}

// ═══════════════════════════════════════════
// Main Workflow
// ═══════════════════════════════════════════

export async function morningBriefWorkflow() {
  'use workflow';

  const date = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  // Gather data from all sources in parallel (each is a separate step)
  const github = await gatherGitHubActivity();
  const docker = await gatherDockerStatus();
  const memory = await gatherMemoryAndPlans();

  // Generate the brief
  const brief = await generateBrief({ github, docker, memory, date });

  // Store it
  const result = await storeBrief(brief, date);

  return {
    success: true,
    date,
    briefLength: brief.length,
    stored: result.stored,
    sections: {
      repos: github.repos.length,
      commits: github.totalCommits7d,
      containers: docker.containers.length,
      plans: memory.plans.length,
    },
  };
}
