import { Clock, Flame, Sparkles } from 'lucide-react';
import HeroSpotlight from './HeroSpotlight';
import CarouselRow from './CarouselRow';
import CinemaCard from './CinemaCard';

const PLACEHOLDER_SPOTLIGHT = [
  {
    id: 'spotlight-1',
    title: 'Welcome to MCV Files',
    subtitle: 'Your unified data fabric across all ventures and storage providers',
    aiSummary: 'Upload files, connect storage providers, and let AI organize everything for you.',
    provider: 'supabase' as const,
    ventureLabel: 'MCV ONE',
    ventureColor: 'var(--cyan)',
  },
];

export default function DiscoverView() {
  return (
    <div className="discover-view">
      <HeroSpotlight items={PLACEHOLDER_SPOTLIGHT} />

      <CarouselRow title="Continue Working" icon={Clock} accentColor="var(--cyan)">
        <CinemaCard
          id="cw-1" title="Getting Started" meta="Just now · Supabase" provider="supabase"
          size="md"
        />
      </CarouselRow>

      <CarouselRow title="Hot Across Ventures" icon={Flame} accentColor="var(--error)">
        <CinemaCard
          id="hv-1" title="No trending files yet" meta="Upload to get started" provider="supabase"
          size="md"
        />
      </CarouselRow>

      <CarouselRow title="Recently Generated by AI" icon={Sparkles} accentColor="var(--purple)">
        <CinemaCard
          id="ai-1" title="No AI-generated content yet" meta="Use Aegis to generate" provider="supabase"
          size="md"
        />
      </CarouselRow>
    </div>
  );
}
