import type { KitManifest, KitToolHandler, KitExecutionContext } from '../types';
async function bingApi(action: string, params: Record<string, unknown>, ctx: KitExecutionContext) {
  const q = new URLSearchParams({ action, ...Object.fromEntries(Object.entries(params).filter(([, v]) => v != null).map(([k, v]) => [k, String(v)])) }).toString();
  const r = await ctx.fetch(`/api/bing?${q}`); if (!r.ok) { const e = await r.json().catch(() => ({})); throw new Error(e.error || 'Bing error'); } return r.json();
}
const webSearch: KitToolHandler = async (input, ctx) => { const d = await bingApi('web-search', { q: input.query, count: input.limit ?? 10, freshness: input.freshness }, ctx); const pages = d.webPages?.value ?? []; const lines = pages.map((p: { name: string; url: string; snippet: string }) => `- **[${p.name}](${p.url})**\n  ${p.snippet?.slice(0, 120)}`); return { success: true, data: pages, displayMarkdown: `## Bing: "${input.query}" (${pages.length})\n\n${lines.join('\n')}` }; };
const newsSearch: KitToolHandler = async (input, ctx) => { const d = await bingApi('news-search', { q: input.query, count: input.limit ?? 10, category: input.category }, ctx); const articles = d.value ?? []; const lines = articles.map((a: { name: string; url: string; description: string; provider: { name: string }[] }) => `- **${a.name}** (${a.provider?.[0]?.name || ''})\n  ${a.description?.slice(0, 100)}`); return { success: true, data: articles, displayMarkdown: `## News: "${input.query || 'trending'}" (${articles.length})\n\n${lines.join('\n')}` }; };
const imageSearch: KitToolHandler = async (input, ctx) => { const d = await bingApi('image-search', { q: input.query, count: input.limit ?? 8, size: input.size }, ctx); const imgs = d.value ?? []; const lines = imgs.map((i: { name: string; thumbnailUrl: string; hostPageUrl: string }) => `- **${i.name}** — [source](${i.hostPageUrl})`); return { success: true, data: imgs, displayMarkdown: `## Images: "${input.query}" (${imgs.length})\n\n${lines.join('\n')}` }; };
const videoSearch: KitToolHandler = async (input, ctx) => { const d = await bingApi('video-search', { q: input.query, count: input.limit ?? 8 }, ctx); const vids = d.value ?? []; const lines = vids.map((v: { name: string; hostPageUrl: string; publisher: { name: string }[]; duration: string }) => `- **${v.name}** (${v.publisher?.[0]?.name || ''}) — ${v.duration || ''}`); return { success: true, data: vids, displayMarkdown: `## Videos: "${input.query}" (${vids.length})\n\n${lines.join('\n')}` }; };
const entitySearch: KitToolHandler = async (input, ctx) => { const d = await bingApi('entity-search', { q: input.query }, ctx); const entities = d.entities?.value ?? []; const lines = entities.map((e: { name: string; description: string; entityPresentationInfo: { entityTypeDisplayHint: string } }) => `- **${e.name}** (${e.entityPresentationInfo?.entityTypeDisplayHint || ''})\n  ${e.description?.slice(0, 120)}`); return { success: true, data: entities, displayMarkdown: `## Entity: "${input.query}"\n\n${lines.join('\n')}` }; };
const trendingNews: KitToolHandler = async (_i, ctx) => { const d = await bingApi('trending-news', {}, ctx); const topics = d.value ?? []; const lines = topics.map((t: { name: string; query: { text: string } }) => `- **${t.name}** — "${t.query?.text}"`); return { success: true, data: topics, displayMarkdown: `## Trending News (${topics.length})\n\n${lines.join('\n')}` }; };
export const manifest: KitManifest = {
  id: 'bing-search', name: 'Bing Search', version: '1.0.0',
  description: 'Bing — web search, news, images, videos, entities, trending, autosuggest, and spell check.',
  author: 'MCV', capabilities: ['network', 'credentials'], runtime: 'inline', ventureScope: '*',
  instructions: 'Use bing tools for web search, news discovery, image/video search, entity knowledge, and trending topics.',
  tools: [
    { name: 'bing_search', description: 'Search the web via Bing.', input_schema: { type: 'object', properties: { query: { type: 'string' }, limit: { type: 'number' }, freshness: { type: 'string', description: 'Day, Week, Month' } }, required: ['query'] } },
    { name: 'bing_news', description: 'Search news or get by category.', input_schema: { type: 'object', properties: { query: { type: 'string' }, limit: { type: 'number' }, category: { type: 'string', description: 'Business, Entertainment, Health, etc.' } } } },
    { name: 'bing_images', description: 'Search images.', input_schema: { type: 'object', properties: { query: { type: 'string' }, limit: { type: 'number' }, size: { type: 'string', description: 'Small, Medium, Large, Wallpaper' } }, required: ['query'] } },
    { name: 'bing_videos', description: 'Search videos.', input_schema: { type: 'object', properties: { query: { type: 'string' }, limit: { type: 'number' } }, required: ['query'] } },
    { name: 'bing_entity', description: 'Look up entity knowledge (people, places, things).', input_schema: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'] } },
    { name: 'bing_trending', description: 'Get trending news topics.', input_schema: { type: 'object', properties: {} } },
  ],
};
export const handlers: Record<string, KitToolHandler> = { bing_search: webSearch, bing_news: newsSearch, bing_images: imageSearch, bing_videos: videoSearch, bing_entity: entitySearch, bing_trending: trendingNews };
